name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: |
          go build -ldflags="-s -w" -o TINKR-Toolkit.exe

      - name: Verify executable exists
        shell: pwsh
        run: |
          if (-not (Test-Path "TINKR-Toolkit.exe")) {
            Write-Host "Executable not found!"
            exit 1
          }
          Write-Host "Executable found successfully."

      - name: Delete existing release if present
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: ${{ github.ref_name }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: TINKR-Toolkit.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
